# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'defineOutputByRwforcFile.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_rwforcFileReader(object):
    def setupUi(self, rwforcFileReader):
        rwforcFileReader.setObjectName("rwforcFileReader")
        rwforcFileReader.resize(853, 677)
        self.verticalLayout = QtWidgets.QVBoxLayout(rwforcFileReader)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setVerticalSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.label_name = QtWidgets.QLabel(rwforcFileReader)
        self.label_name.setMinimumSize(QtCore.QSize(0, 30))
        self.label_name.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_name.setObjectName("label_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_name)
        self.lineEdit_name = QtWidgets.QLineEdit(rwforcFileReader)
        self.lineEdit_name.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_name.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_name)
        self.label_rigidID = QtWidgets.QLabel(rwforcFileReader)
        self.label_rigidID.setMinimumSize(QtCore.QSize(0, 30))
        self.label_rigidID.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_rigidID.setObjectName("label_rigidID")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_rigidID)
        self.cbb_rigidID = QtWidgets.QComboBox(rwforcFileReader)
        self.cbb_rigidID.setMinimumSize(QtCore.QSize(0, 30))
        self.cbb_rigidID.setMaximumSize(QtCore.QSize(16777215, 30))
        self.cbb_rigidID.setObjectName("cbb_rigidID")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cbb_rigidID)
        self.label_direction = QtWidgets.QLabel(rwforcFileReader)
        self.label_direction.setMinimumSize(QtCore.QSize(0, 30))
        self.label_direction.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_direction.setObjectName("label_direction")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_direction)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cbb_direction = QtWidgets.QComboBox(rwforcFileReader)
        self.cbb_direction.setMinimumSize(QtCore.QSize(0, 30))
        self.cbb_direction.setMaximumSize(QtCore.QSize(16777215, 30))
        self.cbb_direction.setObjectName("cbb_direction")
        self.horizontalLayout.addWidget(self.cbb_direction)
        self.cbb_func = QtWidgets.QComboBox(rwforcFileReader)
        self.cbb_func.setMinimumSize(QtCore.QSize(0, 30))
        self.cbb_func.setMaximumSize(QtCore.QSize(16777215, 30))
        self.cbb_func.setObjectName("cbb_func")
        self.horizontalLayout.addWidget(self.cbb_func)
        self.label_finalResult = QtWidgets.QLabel(rwforcFileReader)
        self.label_finalResult.setMinimumSize(QtCore.QSize(0, 30))
        self.label_finalResult.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_finalResult.setObjectName("label_finalResult")
        self.horizontalLayout.addWidget(self.label_finalResult)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.verticalLayout.addLayout(self.formLayout)
        self.widget_chart = myLineChart(rwforcFileReader)
        self.widget_chart.setObjectName("widget_chart")
        self.verticalLayout.addWidget(self.widget_chart)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.Btn_yes = QtWidgets.QPushButton(rwforcFileReader)
        self.Btn_yes.setMinimumSize(QtCore.QSize(80, 40))
        self.Btn_yes.setMaximumSize(QtCore.QSize(80, 40))
        self.Btn_yes.setObjectName("Btn_yes")
        self.horizontalLayout_2.addWidget(self.Btn_yes)
        self.Btn_cancel = QtWidgets.QPushButton(rwforcFileReader)
        self.Btn_cancel.setMinimumSize(QtCore.QSize(80, 40))
        self.Btn_cancel.setMaximumSize(QtCore.QSize(80, 40))
        self.Btn_cancel.setObjectName("Btn_cancel")
        self.horizontalLayout_2.addWidget(self.Btn_cancel)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout.setStretch(1, 1)

        self.retranslateUi(rwforcFileReader)
        QtCore.QMetaObject.connectSlotsByName(rwforcFileReader)

    def retranslateUi(self, rwforcFileReader):
        _translate = QtCore.QCoreApplication.translate
        rwforcFileReader.setWindowTitle(_translate("rwforcFileReader", "rwforc文件结果读取"))
        self.label_name.setText(_translate("rwforcFileReader", "名称"))
        self.label_rigidID.setText(_translate("rwforcFileReader", "rigid ID"))
        self.label_direction.setText(_translate("rwforcFileReader", "方向"))
        self.label_finalResult.setText(_translate("rwforcFileReader", "（x:；y: ）"))
        self.Btn_yes.setText(_translate("rwforcFileReader", "确定"))
        self.Btn_cancel.setText(_translate("rwforcFileReader", "取消"))
from PublicTool.myLineChart import myLineChart
