# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'myTextEdit.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_myTextEdit(object):
    def setupUi(self, myTextEdit):
        myTextEdit.setObjectName("myTextEdit")
        myTextEdit.resize(952, 762)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(myTextEdit)
        self.verticalLayout_2.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_2.setSpacing(20)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textEdit_row = QtWidgets.QTextEdit(myTextEdit)
        self.textEdit_row.setMinimumSize(QtCore.QSize(0, 0))
        self.textEdit_row.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.textEdit_row.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_row.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_row.setObjectName("textEdit_row")
        self.horizontalLayout.addWidget(self.textEdit_row)
        self.textEdit_text = QtWidgets.QTextEdit(myTextEdit)
        self.textEdit_text.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_text.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.textEdit_text.setObjectName("textEdit_text")
        self.horizontalLayout.addWidget(self.textEdit_text)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.widget = QtWidgets.QWidget(myTextEdit)
        self.widget.setMinimumSize(QtCore.QSize(0, 20))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 20))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_fileName = QtWidgets.QLabel(self.widget)
        self.label_fileName.setObjectName("label_fileName")
        self.horizontalLayout_2.addWidget(self.label_fileName)
        self.label_locaInfo = QtWidgets.QLabel(self.widget)
        self.label_locaInfo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_locaInfo.setObjectName("label_locaInfo")
        self.horizontalLayout_2.addWidget(self.label_locaInfo)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout.addWidget(self.widget)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(myTextEdit)
        self.pushButton.setMinimumSize(QtCore.QSize(80, 40))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.horizontalLayout_3.setStretch(0, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)

        self.retranslateUi(myTextEdit)
        QtCore.QMetaObject.connectSlotsByName(myTextEdit)

    def retranslateUi(self, myTextEdit):
        _translate = QtCore.QCoreApplication.translate
        myTextEdit.setWindowTitle(_translate("myTextEdit", "Form"))
        self.label_fileName.setText(_translate("myTextEdit", "文件名"))
        self.label_locaInfo.setText(_translate("myTextEdit", "Ln:        Col:               "))
        self.pushButton.setText(_translate("myTextEdit", "确定"))
