# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setVariableDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_setVariable(object):
    def setupUi(self, setVariable):
        setVariable.setObjectName("setVariable")
        setVariable.resize(580, 227)
        self.verticalLayout = QtWidgets.QVBoxLayout(setVariable)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 52, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setHorizontalSpacing(6)
        self.formLayout.setVerticalSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.label_variableName = QtWidgets.QLabel(setVariable)
        self.label_variableName.setMinimumSize(QtCore.QSize(0, 20))
        self.label_variableName.setObjectName("label_variableName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_variableName)
        self.lineEdit_variableName = QtWidgets.QLineEdit(setVariable)
        self.lineEdit_variableName.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_variableName.setObjectName("lineEdit_variableName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_variableName)
        self.label_valueRange = QtWidgets.QLabel(setVariable)
        self.label_valueRange.setMinimumSize(QtCore.QSize(0, 20))
        self.label_valueRange.setObjectName("label_valueRange")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_valueRange)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_lowRange = QtWidgets.QLineEdit(setVariable)
        self.lineEdit_lowRange.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_lowRange.setObjectName("lineEdit_lowRange")
        self.horizontalLayout.addWidget(self.lineEdit_lowRange)
        self.line = QtWidgets.QFrame(setVariable)
        self.line.setMinimumSize(QtCore.QSize(10, 0))
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.lineEdit_upRange = QtWidgets.QLineEdit(setVariable)
        self.lineEdit_upRange.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit_upRange.setObjectName("lineEdit_upRange")
        self.horizontalLayout.addWidget(self.lineEdit_upRange)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.horizontalLayout_3.addLayout(self.formLayout)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.label_err = QtWidgets.QLabel(setVariable)
        self.label_err.setMinimumSize(QtCore.QSize(0, 30))
        self.label_err.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_err.setText("")
        self.label_err.setAlignment(QtCore.Qt.AlignCenter)
        self.label_err.setObjectName("label_err")
        self.verticalLayout.addWidget(self.label_err)
        spacerItem3 = QtWidgets.QSpacerItem(20, 52, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.Btn_ok = QtWidgets.QPushButton(setVariable)
        self.Btn_ok.setMinimumSize(QtCore.QSize(80, 40))
        self.Btn_ok.setMaximumSize(QtCore.QSize(80, 40))
        self.Btn_ok.setObjectName("Btn_ok")
        self.horizontalLayout_2.addWidget(self.Btn_ok)
        self.Btn_cancel = QtWidgets.QPushButton(setVariable)
        self.Btn_cancel.setMinimumSize(QtCore.QSize(80, 40))
        self.Btn_cancel.setMaximumSize(QtCore.QSize(80, 40))
        self.Btn_cancel.setObjectName("Btn_cancel")
        self.horizontalLayout_2.addWidget(self.Btn_cancel)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(setVariable)
        QtCore.QMetaObject.connectSlotsByName(setVariable)

    def retranslateUi(self, setVariable):
        _translate = QtCore.QCoreApplication.translate
        setVariable.setWindowTitle(_translate("setVariable", "Form"))
        self.label_variableName.setText(_translate("setVariable", "变量名"))
        self.label_valueRange.setText(_translate("setVariable", "取值范围"))
        self.Btn_ok.setText(_translate("setVariable", "确定"))
        self.Btn_cancel.setText(_translate("setVariable", "取消"))
