# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ResultsWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ResultsWidget(object):
    def setupUi(self, ResultsWidget):
        ResultsWidget.setObjectName("ResultsWidget")
        ResultsWidget.resize(869, 638)
        self.verticalLayout = QtWidgets.QVBoxLayout(ResultsWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(ResultsWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.Btn_quit = QtWidgets.QPushButton(ResultsWidget)
        self.Btn_quit.setMinimumSize(QtCore.QSize(80, 40))
        self.Btn_quit.setObjectName("Btn_quit")
        self.horizontalLayout.addWidget(self.Btn_quit)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(ResultsWidget)
        QtCore.QMetaObject.connectSlotsByName(ResultsWidget)

    def retranslateUi(self, ResultsWidget):
        _translate = QtCore.QCoreApplication.translate
        ResultsWidget.setWindowTitle(_translate("ResultsWidget", "Form"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("ResultsWidget", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("ResultsWidget", "Tab 2"))
        self.Btn_quit.setText(_translate("ResultsWidget", "退出"))
