# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SensitiveAnalyseResults.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1042, 711)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_SAWays = QtWidgets.QLabel(Form)
        self.label_SAWays.setMinimumSize(QtCore.QSize(0, 30))
        self.label_SAWays.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_SAWays.setObjectName("label_SAWays")
        self.horizontalLayout.addWidget(self.label_SAWays)
        self.lineEdit_SAWays = QtWidgets.QLineEdit(Form)
        self.lineEdit_SAWays.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_SAWays.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lineEdit_SAWays.setObjectName("lineEdit_SAWays")
        self.horizontalLayout.addWidget(self.lineEdit_SAWays)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.label = QtWidgets.QLabel(Form)
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_chooseOutput = QtWidgets.QLabel(Form)
        self.label_chooseOutput.setMinimumSize(QtCore.QSize(0, 30))
        self.label_chooseOutput.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_chooseOutput.setObjectName("label_chooseOutput")
        self.horizontalLayout_2.addWidget(self.label_chooseOutput)
        self.cbb_chooseOutput = QtWidgets.QComboBox(Form)
        self.cbb_chooseOutput.setMinimumSize(QtCore.QSize(0, 30))
        self.cbb_chooseOutput.setMaximumSize(QtCore.QSize(16777215, 30))
        self.cbb_chooseOutput.setObjectName("cbb_chooseOutput")
        self.horizontalLayout_2.addWidget(self.cbb_chooseOutput)
        self.horizontalLayout_2.setStretch(1, 1)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.splitter = QtWidgets.QSplitter(Form)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.tableWidget = QtWidgets.QTableWidget(self.splitter)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_pieShowNum = QtWidgets.QLabel(self.widget)
        self.label_pieShowNum.setMinimumSize(QtCore.QSize(0, 30))
        self.label_pieShowNum.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_pieShowNum.setObjectName("label_pieShowNum")
        self.horizontalLayout_4.addWidget(self.label_pieShowNum)
        self.lineEdit_pieShowNum = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_pieShowNum.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_pieShowNum.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lineEdit_pieShowNum.setText("")
        self.lineEdit_pieShowNum.setObjectName("lineEdit_pieShowNum")
        self.horizontalLayout_4.addWidget(self.lineEdit_pieShowNum)
        self.horizontalLayout_4.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.widget_pieChart = myLineChart(self.widget)
        self.widget_pieChart.setObjectName("widget_pieChart")
        self.verticalLayout.addWidget(self.widget_pieChart)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout_2.addWidget(self.splitter)
        self.verticalLayout_2.setStretch(1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_SAWays.setText(_translate("Form", "当前敏感性分析方法："))
        self.label_chooseOutput.setText(_translate("Form", "选择目标响应值："))
        self.label_pieShowNum.setText(_translate("Form", "排序指标显示数量："))
from PublicTool.myLineChart import myLineChart
